In [1]:
import pandas as pd
import numpy as np

In [2]:
college = pd.read_csv('../data/college.csv', index_col='INSTNM')
city = college['CITY']
city.head()

INSTNM
Alabama A & M University                   Normal
University of Alabama at Birmingham    Birmingham
Amridge University                     Montgomery
University of Alabama in Huntsville    Huntsville
Alabama State University               Montgomery
Name: CITY, dtype: object

In [3]:
city.iloc[3]

'Huntsville'

In [4]:
city.iloc[[10, 20, 30]]

INSTNM
Birmingham Southern College                            Birmingham
George C Wallace State Community College-Hanceville    Hanceville
Judson College                                             Marion
Name: CITY, dtype: object

In [5]:
city.iloc[4:50:10]

INSTNM
Alabama State University              Montgomery
Enterprise State Community College    Enterprise
Heritage Christian University           Florence
Marion Military Institute                 Marion
Reid State Technical College           Evergreen
Name: CITY, dtype: object

In [6]:
city.loc['Heritage Christian University']

'Florence'

In [7]:
np.random.seed(1)

In [8]:
labels = list(np.random.choice(city.index, 4))

In [9]:
labels

['Northwest HVAC/R Training Center',
 'California State University-Dominguez Hills',
 'Lower Columbia College',
 'Southwest Acupuncture College-Boulder']

In [10]:
city.loc[labels]

INSTNM
Northwest HVAC/R Training Center                Spokane
California State University-Dominguez Hills      Carson
Lower Columbia College                         Longview
Southwest Acupuncture College-Boulder           Boulder
Name: CITY, dtype: object

In [12]:
college.iloc[60]

CITY                  Anchorage
STABBR                       AK
HBCU                          0
MENONLY                       0
WOMENONLY                     0
RELAFFIL                      0
SATVRMID                    NaN
SATMTMID                    NaN
DISTANCEONLY                  0
UGDS                      12865
UGDS_WHITE               0.5747
UGDS_BLACK               0.0358
UGDS_HISP                0.0761
UGDS_ASIAN               0.0778
UGDS_AIAN                0.0653
UGDS_NHPI                0.0086
UGDS_2MOR                 0.098
UGDS_NRA                 0.0181
UGDS_UNKN                0.0457
PPTUG_EF                 0.4539
CURROPER                      1
PCTPELL                  0.2385
PCTFLOAN                 0.2647
UG25ABV                  0.4386
MD_EARN_WNE_P10           42500
GRAD_DEBT_MDN_SUPP      19449.5
Name: University of Alaska Anchorage, dtype: object

In [14]:
college.iloc[[60, 93, 30]]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
University of Alaska Anchorage,Anchorage,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,12865.0,...,0.0980,0.0181,0.0457,0.4539,1,0.2385,0.2647,0.4386,42500,19449.5
Avalon School of Cosmetology-Mesa,Mesa,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,360.0,...,0.0250,0.0000,0.0222,0.3667,1,0.6218,0.6495,0.2930,19600,11458
Judson College,Marion,AL,0.0,0.0,1.0,1,NaN,NaN,0.0,376.0,...,0.0053,0.0133,0.0319,0.2926,1,0.4784,0.7205,0.2622,29300,PrivacySuppressed

In [15]:
college.loc[['University of Alaska Anchorage', 'Avalon School of Cosmetology-Mesa']]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
University of Alaska Anchorage,Anchorage,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,12865.0,...,0.098,0.0181,0.0457,0.4539,1,0.2385,0.2647,0.4386,42500,19449.5
Avalon School of Cosmetology-Mesa,Mesa,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,360.0,...,0.025,0.0000,0.0222,0.3667,1,0.6218,0.6495,0.2930,19600,11458

In [16]:
lables = [['University of Alaska Anchorage', 'Avalon School of Cosmetology-Mesa']]

In [17]:
college.loc[['University of Alaska Anchorage', 'Avalon School of Cosmetology-Mesa']]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
University of Alaska Anchorage,Anchorage,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,12865.0,...,0.098,0.0181,0.0457,0.4539,1,0.2385,0.2647,0.4386,42500,19449.5
Avalon School of Cosmetology-Mesa,Mesa,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,360.0,...,0.025,0.0000,0.0222,0.3667,1,0.6218,0.6495,0.2930,19600,11458

In [19]:
labels_test = college.iloc[[3, 10, 15]].index.tolist()

In [21]:
college.loc[labels_test]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Birmingham Southern College,Birmingham,AL,0.0,0.0,0.0,1,560.0,560.0,0.0,1180.0,...,0.0051,0.0000,0.0051,0.0017,1,0.1920,0.4809,0.0152,44200,27000
James H Faulkner State Community College,Bay Minette,AL,0.0,0.0,0.0,0,NaN,NaN,0.0,4286.0,...,0.0152,0.0007,0.0009,0.4104,1,0.4725,0.3741,0.2909,28700,11000

In [23]:
college.loc[:'University of Alabama in Huntsville', :'RELAFFIL']

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL
INSTNM,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0
Amridge University,Montgomery,AL,0.0,0.0,0.0,1
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0

In [24]:
college.iloc[:3, :6]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL
INSTNM,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0
Amridge University,Montgomery,AL,0.0,0.0,0.0,1

In [25]:
college.iloc[:, [4,6]].head()

                                     WOMENONLY  SATVRMID
INSTNM
Alabama A & M University                   0.0     424.0
University of Alabama at Birmingham        0.0     570.0
Amridge University                         0.0       NaN
University of Alabama in Huntsville        0.0     595.0
Alabama State University                   0.0     425.0

In [36]:
col_ind = college.loc[:, ['WOMENONLY','SATVRMID']]

In [42]:
col_ind.head(1)

                          WOMENONLY  SATVRMID
INSTNM
Alabama A & M University        0.0     424.0

In [37]:
col_colm = college.iloc[:, [7,15]].columns.tolist()

In [38]:
college.loc[['GateWay Community College', 'American Baptist Seminary of the West'],
            ['SATMTMID', 'UGDS_NHPI']]

                                       SATMTMID  UGDS_NHPI
INSTNM
GateWay Community College                   NaN     0.0029
American Baptist Seminary of the West       NaN        NaN

In [43]:
col_ind = college.iloc[[100, 200],].index.tolist()

In [44]:
college.loc[col_ind, col_colm]

                                       SATMTMID  UGDS_NHPI
INSTNM
GateWay Community College                   NaN     0.0029
American Baptist Seminary of the West       NaN        NaN

In [45]:
college.iloc[5, -4]

0.401

In [47]:
college.loc['The University of Alabama', 'PCTFLOAN']

0.401

In [49]:
college.iloc[90:80:-2, 5]

INSTNM
Empire Beauty School-Flagstaff     0
Charles of Italy Beauty College    0
Central Arizona College            0
University of Arizona              0
Arizona State University-Tempe     0
Name: RELAFFIL, dtype: int64

In [50]:
col_start = college.columns.get_loc('UGDS_WHITE')

In [54]:
col_stop = college.columns.get_loc('UGDS_UNKN') + 1

In [55]:
college.iloc[:5, col_start:col_stop]

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

In [57]:
college = college.sort_index()

In [66]:
college.loc['By':'D'].head(50)

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Byzantine Catholic Seminary of Saints Cyril and Methodius,Pittsburgh,PA,0.0,0.0,0.0,1,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,PrivacySuppressed
CALC Institute of Technology,Alton,IL,0.0,0.0,0.0,0,NaN,NaN,0.0,174.0,...,0.0230,0.0000,0.0057,0.9253,1,0.6509,0.4497,0.5721,PrivacySuppressed,8636
CBD College,Los Angeles,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,411.0,...,0.0000,0.0000,0.0000,0.0000,1,0.8790,0.9849,0.5609,14200,13000
CBTS - Wisconsin,Elm Grove,WI,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,PrivacySuppressed
CC's Cosmetology College,Tulsa,OK,0.0,0.0,0.0,0,NaN,NaN,0.0,46.0,...,0.0000,0.0000,0.0000,0.0000,1,0.6190,0.7381,0.5532,14800,PrivacySuppressed
CC's Cosmetology College-Texarkana,Texarkana,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,14800,PrivacySuppressed
CCI Training Center,Dallas,TX,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,8313
CCI Training Center-Arlington,Arlington,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,209.0,...,0.0478,0.0000,0.0096,0.2584,1,0.7631,0.5537,0.6281,PrivacySuppressed,8313
CDA Technical Institute,Jacksonville,FL,0.0,0.0,0.0,0,NaN,NaN,0.0,190.0,...,0.0158,0.0053,0.0000,0.0000,1,0.4020,0.6458,0.5067,PrivacySuppressed,7307
CDE Career Institute,Tannersville,PA,0.0,0.0,0.0,0,NaN,NaN,0.0,31.0,...,0.0000,0.0000,0.0000,0.0000,1,0.4545,0.3247,0.6809,NaN,PrivacySuppressed
CES College,Burbank,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,140.0,...,0.0000,0.0071,0.0286,0.0571,1,0.7868,0.4147,0.8012,PrivacySuppressed,17165.5
CET-Alexandria,Alexandria,VA,0.0,0.0,0.0,0,NaN,NaN,0.0,187.0,...,0.0000,0.0000,0.0000,0.7487,1,0.5842,0.5125,0.8225,21700,5402
CET-Chicago,Chicago,IL,0.0,0.0,0.0,1,NaN,NaN,0.0,151.0,...,0.0066,0.0000,0.0000,0.0000,0,0.9744,0.7920,0.4880,21700,5402
CET-Coachella,Coachella,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,139.0,...,0.0072,0.0000,0.0000,0.4245,1,0.5725,0.2634,0.3797,21700,5402
CET-Durham,Durham,NC,0.0,0.0,0.0,0,NaN,NaN,0.0,132.0,...,0.0227,0.0000,0.0000,0.2879,1,0.7360,0.6040,0.6940,21700,5402
CET-El Centro,El Centro,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,260.0,...,0.0000,0.0000,0.0000,0.0000,1,0.3157,0.0728,0.5897,21700,5402
CET-El Paso,El Paso,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,113.0,...,0.0000,0.0000,0.0000,0.0000,1,0.7356,0.6058,0.7879,21700,5402
CET-Oxnard,Oxnard,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,119.0,...,0.0000,0.0000,0.0000,0.0252,1,0.4048,0.3238,0.3383,21700,5402
CET-Sacramento,Sacramento,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,151.0,...,0.0331,0.0000,0.0000,0.0000,1,0.6877,0.3018,0.6483,21700,5402
CET-Salinas,Salinas,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,54.0,...,0.0000,0.0000,0.0000,0.0000,1,0.2536,0.0870,0.4462,21700,5402
CET-San Bernardino,San Bernardino,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,116.0,...,0.0172,0.0000,0.0000,0.0000,1,0.6955,0.5409,0.6117,21700,5402
CET-San Diego,San Diego,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,253.0,...,0.0040,0.0000,0.0000,0.3715,1,0.5969,0.3922,0.6330,21700,5402
CET-Santa Maria,Santa Maria,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,145.0,...,0.0276,0.0000,0.0000,0.4000,1,0.5211,0.3563,0.2516,21700,5402
CET-Sobrato,San Jose,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,327.0,...,0.0122,0.0000,0.0000,0.0031,1,0.5589,0.4019,0.5072,21700,5402
CET-Soledad,Soledad,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,94.0,...,0.0000,0.0000,0.0000,0.0000,1,0.4780,0.2088,0.2990,21700,5402
CET-Watsonville,Watsonville,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,96.0,...,0.0000,0.0000,0.0000,0.0000,1,0.3518,0.1206,0.2727,21700,5402
CHI Health School of Radiologic Technology,Omaha,NE,0.0,0.0,0.0,1,NaN,NaN,0.0,22.0,...,0.0000,0.0000,0.0000,0.0000,1,0.0909,0.5455,0.2273,PrivacySuppressed,PrivacySuppressed
CHOICE High School and Technical Center,Fort Walton Beach,FL,0.0,0.0,0.0,0,NaN,NaN,0.0,321.0,...,0.0156,0.0000,0.0000,0.1963,1,0.4654,0.0000,0.6418,26900,PrivacySuppressed
COBA Academy,Orange,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,36.0,...,0.0000,0.0000,0.0000,0.0000,1,0.6000,0.6000,0.2500,PrivacySuppressed,11670.5
CRU Institute,Garden Grove,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,49.0,...,0.0408,0.0204,0.0000,0.1429,1,0.6543,0.6296,0.0909,13200,9833
CUNY Bernard M Baruch College,New York,NY,0.0,0.0,0.0,0,590.0,645.0,0.0,14420.0,...,0.0138,0.1167,0.0000,0.2513,1,0.4401,0.1758,0.2613,54900,11000
CUNY Borough of Manhattan Community College,New York,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,25849.0,...,0.0157,0.0598,0.0000,0.3384,1,0.6757,0.1033,0.2504,34500,7500
CUNY Bronx Community College,Bronx,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,10685.0,...,0.0066,0.0229,0.0000,0.3608,1,0.6775,0.0982,0.3439,32100,7720
CUNY Brooklyn College,Brooklyn,NY,0.0,0.0,0.0,0,525.0,560.0,0.0,12925.0,...,0.0149,0.0299,0.0000,0.2409,1,0.4879,0.2179,0.2761,44500,10456
CUNY City College,New York,NY,0.0,0.0,0.0,0,535.0,595.0,0.0,12175.0,...,0.0166,0.0671,0.0000,0.2362,1,0.5180,0.2225,0.2353,45800,11551
CUNY Graduate School and University Center,New York,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,1297.0,...,0.0023,0.0015,0.0000,0.7379,1,0.2316,0.2042,0.8961,PrivacySuppressed,9318
CUNY Hostos Community College,Bronx,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,6389.0,...,0.0074,0.0521,0.0000,0.3677,1,0.6844,0.0735,0.3436,30700,7000
CUNY Hunter College,New York,NY,0.0,0.0,0.0,0,565.0,595.0,0.0,15778.0,...,0.0165,0.0631,0.0000,0.2353,1,0.4209,0.1819,0.2224,45000,10053
CUNY John Jay College of Criminal Justice,New York,NY,0.0,0.0,0.0,0,475.0,495.0,0.0,12758.0,...,0.0154,0.0292,0.0000,0.1990,1,0.5530,0.2067,0.2011,42400,10092
CUNY Kingsborough Community College,Brooklyn,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,13625.0,...,0.0139,0.0335,0.0000,0.2539,1,0.4908,0.0742,0.2260,35300,6032
CUNY LaGuardia Community College,Long Island City,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,17069.0,...,0.0106,0.0818,0.0000,0.3688,1,0.4869,0.0544,0.2876,32600,5500
CUNY Lehman College,Bronx,NY,0.0,0.0,0.0,0,495.0,500.0,0.0,9417.0,...,0.0052,0.0360,0.0000,0.3773,1,0.5310,0.2199,0.4516,40400,10000
CUNY Medgar Evers College,Brooklyn,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,6241.0,...,0.0139,0.0306,0.0000,0.3200,1,0.6181,0.2143,0.4312,35000,8350
CUNY New York City College of Technology,Brooklyn,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,16354.0,...,0.0099,0.0472,0.0000,0.3591,1,0.5620,0.1517,0.2853,37500,10101.5
CUNY Queens College,Queens,NY,0.0,0.0,0.0,0,520.0,570.0,0.0,14842.0,...,0.0090,0.0477,0.0000,0.2548,1,0.3868,0.1522,0.2501,47500,11000
CUNY Queensborough Community College,Bayside,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,14197.0,...,0.0115,0.0552,0.0000,0.3292,1,0.4946,0.0616,0.2012,35600,7843
CUNY School of Law,Long Island City,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,67100,PrivacySuppressed
CUNY York College,Jamaica,NY,0.0,0.0,0.0,0,435.0,465.0,0.0,7245.0,...,0.0095,0.0422,0.0000,0.3003,1,0.5279,0.1028,0.2812,38700,9500
CVPH Medical Center School of Radiologic Technology,Plattsburgh,NY,0.0,0.0,0.0,0,NaN,NaN,0.0,23.0,...,0.0000,0.0000,0.0000,0.0000,1,0.4348,0.9130,0.1739,PrivacySuppressed,PrivacySuppressed
Cabarrus College of Health Sciences,Concord,NC,0.0,0.0,0.0,0,465.0,495.0,0.0,434.0,...,0.0161,0.0000,0.0000,0.6014,1,0.3858,0.7361,0.5255,40700,15800